### ISSUE TITLE
Time Issue - import IGC - WebBrowser

### ISSUE THREAD

**Issue by Sqefs** [laggery/Flightbook-MobileApp#23]
First, many thanks for your application that I'have been using for quite a while now !

I try your new import IGC feature and I have an issue with the time detection. 

My flight was about 55 minutes on LogFly, and is detected as 11 minutes by your focntion.

![image](https://user-images.githubusercontent.com/94315642/141694201-282a3624-2cf1-45f8-97f4-7d3b90eddca6.png)

![Test](https://user-images.githubusercontent.com/94315642/141694105-70e4c41b-e025-4f8d-ae18-a11c19b8487e.JPG)

[Test.zip](https://github.com/laggery/Flightbook-MobileApp/files/7534404/Test.zip)

I don't know fi you can fix it !

Many Thanks again !

David

**Comment by fabiangotzen** [comment]
Hi David
Thank you for using flightbook! We will have a look into it and let you know as soon as we have found the issue.

**Comment by laggery** [comment]
Hi David

Thank you for reporting this issue.
During the first third of the flight, I have no altitude and time data but the gps coordinates are recorded. Printscreen below.
<img width="633" alt="Screenshot 2021-12-02 at 17 18 58" src="https://user-images.githubusercontent.com/2563295/144461908-e9258f81-d5c7-41e5-a6cd-a6266bb00691.png">
<img width="642" alt="Screenshot 2021-12-02 at 17 19 17" src="https://user-images.githubusercontent.com/2563295/144462022-29bd07cc-a0d5-4251-80a2-8f6ed2771aa1.png">

Have you this Problem with all your igc Files?

Thanks for your help
Yannick

**Comment by Sqefs** [comment]
Hi,

First many things for checking my issue.

It's weird because for me it works.
![image](https://user-images.githubusercontent.com/94315642/144757748-e5af6b99-bc42-4f91-95c4-e6f77bc1a6cd.png)

Whats weirder is that my file seems correct. I'checked my file :
First instant :
B**114246**3700389N00532462WA00308 **00398** 04204000 --> 11h42'46'' 398m which is coherent with my logfly data.
Second Instant : 
B**114256**3700404N00532483WA00310**00402**04704000 --> 11h42'56''  402m
And so on.

It the first time I'm doing that so I may be wrong.
I'm using this to manually decrypt the test.igc file https://xp-soaring.github.io/igc_file_format/igc_format_2008.html#link_3.4
I'm also using this website to check https://igcviewer.bgaladder.net/. They offset my altitude but it's coherent.

Thanks

David

**Comment by laggery** [comment]
Hi David

I don't know if you are still using the Flightbook but I was able to find the problem. 
I have just deployed the fix to https://m.flightbbok.ch. It will be included in the native app with the next release 2.5.0.

Best regards
Yannick

**Comment by Sqefs** [comment]
Hi Yannick,

Yes I'm still using flightbook and I confirm that it works now !
Many thanks for the debug !

Best regards

David


Le sam. 13 mai 2023 à 01:17, Yannick Lagger ***@***.***> a
écrit :
