### ISSUE TITLE
Kartendarstellung blank

### ISSUE THREAD

**Issue by EulenspiegelTill** [laggery/Flightbook-MobileApp#65]
Beim einfügen eines IGC's kommen Parameter wie Dauer, Strecke und Datum. Die Karte bleibt aber blank (siehe Screenshot).
getestet mit chromium, safari und dem Iphone app.

Gruss Till

<img width="1329" alt="Bildschirmfoto 2024-01-29 um 22 40 42" src="https://github.com/laggery/Flightbook-MobileApp/assets/23494522/69ed6507-c4e5-4d63-b13b-0cfe3e7ace69">

![IMG_9920](https://github.com/laggery/Flightbook-MobileApp/assets/23494522/373b29fd-8d59-4153-912b-a2c09a49d7b1)

**Comment by laggery** [comment]
Hallo Till

Ich danke dir für deine Rückmeldung.

Der Bug konnte ich bereits in der web Applikation korrigieren.
Beim iOS und Android App muss ich noch ein release machen

Gruss
Yannick
